version: '3.9'

services:
  SistemaDeEnviosDB:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssqlserverdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DataPass@2022
    ports:
      - 1450:1433
    restart: always
  sistema-de-envios:
    build:
      dockerfile: "./Dockerfile"
    container_name: sistema-de-envios
    ports:
      - 5000:80
    depends_on:
      - SistemaDeEnviosDB
      - rabbitmq
    restart: always
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    restart: always

networks:
  default:
    name: sd-network
    external: true