AMQP_URI: amqp://admin:adminpass@rabbitmq:5672

LOGGING:
    version: 1
    handlers:
        console:
            class: logging.StreamHandler
    root:
        level: DEBUG
        handlers: [console]
