const ERRORS = {
    USER_NOT_PRESENT: 'USER_NOT_PRESENT',
    NOT_ENOUGH_BALANCE: 'NOT_ENOUGH_BALANCE',
    FAILED_TO_WRITE_PURCHASE: 'FAILED_TO_WRITE_PURCHASE',
    FAILED_TO_SEND_PURCHASE_TO_DELIVERY_SYSTEM: 'FAILED_TO_SEND_PURCHASE_TO_DELIVERY_SYSTEM'
}

module.exports = ERRORS