version: '3.9'

services:
  BlobStorageDB:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: blobstoragedb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DataPass@2022
    ports:
      - 1452:1433
  blob-storage:
    build:
      dockerfile: "./Dockerfile"
    container_name: blob-storage
    ports:
      - 5010:80
    depends_on:
      - BlobStorageDB

# networks:
#   default:
#     name: blob-storage-network
#     external: true
